import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ConfigProvider } from 'antd';
import { black, blackLight, blue, gray, red, white } from '@/constants/colors';
import Navbar from '@/components/navbar/navbar';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ConfigProvider
        theme={{
          components: {
            Pagination: {
              itemActiveBg: blue,
              itemBg: red,
              // itemInputBg: red,
              // itemLinkBg: red,
              colorPrimaryHover: gray,
              colorBgTextHover: blue
            },
            Card: {
              actionsBg: black
            },
          },
          token: {
            colorBgContainer: blackLight,
            colorText: white,
            colorBorderSecondary: blackLight
          },
        }}
      >
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </ConfigProvider>
    </html>
  )
}
